// import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "d6dfff67-2331-4e28-9faf-ea6c25f85b2b",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fe/Bayonetta_3_cover.webp/316px-Bayonetta_3_cover.webp.png",
    title: "Bayonetta 3",
    Publisher: "Nintendo",
    price: 2299,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action"],
    stockQty: 10,
    rating: 3.7,
    releaseDate: "October 28, 2022",
    aboutGame:
      "Bayonetta returns in a new, over-the-top climax action game. Sporting a wicked new ensemble and somehow familiar pigtails, the titular Umbra Witch must face a mysterious evil using her signature guns and time-slowing Witch Time ability.",
  },
  {
    _id: "6ca6701d-6f8b-4b51-a497-47e00e30d205",
    img: "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg",
    title: "Elden Ring",
    Publisher: "Bandai Namco Entertainment",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 14,
    rating: 4.8,
    releaseDate: "January 21, 2022",
    aboutGame:
      "Elden Ring is an expansive world filled with rich lore and tough challenges, crafted by Hidetaka Miyazaki and George R. R. Martin.",
  },
  {
    _id: "83de548b-c56e-4cb2-a1e7-4c17d61bfdf2",
    img: "https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg",
    title: "Forza Horizon 5",
    Publisher: "Xbox Game Studios",
    price: 3499,
    originalPrice: 4999,
    category: "PC Games",
    Genre: ["Racing"],
    stockQty: 30,
    rating: 4.9,
    releaseDate: "November 9, 2021",
    aboutGame:
      "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.",
  },
  {
    _id: "21ff1d6c-7f27-46b7-a96f-25e280d82165",
    img: "https://upload.wikimedia.org/wikipedia/en/3/35/Far_cry_6_cover.jpg",
    title: "Far Cry 6",
    Publisher: "Ubisoft",
    price: 2599,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 25,
    rating: 4.5,
    releaseDate: "October 7, 2021",
    aboutGame:
      "Welcome to Yara, a tropical paradise frozen in time. Far Cry 6 thrusts players into the adrenaline-filled world of a modern-day guerrilla revolution.",
  },
  {
    _id: "7618994c-13a6-4d84-b332-cb9011ea5172",
    img: "https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png",
    title: "Resident Evil Village",
    Publisher: "Capcom",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Survival horror"],
    stockQty: 17,
    rating: 4.7,
    releaseDate: "May 7, 2021",
    aboutGame:
      "Experience survival horror like never before in Resident Evil Village, the eighth major installment in the genre-defining Resident Evil franchise.",
  },
  {
    _id: "8edc82ec-0efe-4954-88e5-0c0db9d043aa",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
    title: "Cyberpunk 2077",
    Publisher: "CD Projekt",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["RPG", "Action"],
    stockQty: 20,
    rating: 4.9,
    releaseDate: "December 10, 2020",
    aboutGame:
      "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification.",
  },
  {
    _id: "847b1810-88a7-4f0e-993c-9261f7a255e1",
    img: "https://upload.wikimedia.org/wikipedia/en/a/a3/Spider-Man_Miles_Morales.jpeg",
    title: "Marvel's Spider-Man: Miles Morales",
    Publisher: "Sony Interactive Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 18,
    rating: 4.7,
    releaseDate: "November 12, 2020",
    aboutGame:
      "In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker.",
  },
  {
    _id: "a8ffabae-09f8-4cbd-b2c4-f71a9fbb5bb8",
    img: "https://upload.wikimedia.org/wikipedia/en/f/ff/Assassin%27s_Creed_Valhalla_cover.jpg",
    title: "Assassin's Creed Valhalla",
    Publisher: "Ubisoft",
    price: 2599,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 22,
    rating: 4.5,
    releaseDate: "November 10, 2020",
    aboutGame:
      "In Assassin's Creed Valhalla, become Eivor, a legendary Viking warrior on a quest for glory.",
  },
  {
    _id: "6fd5dfde-cf18-4988-97e9-841b8796cfb5",
    img: "https://assets-prd.ignimgs.com/2020/09/29/genshin-impact-button-fin-1601346152039.jpg",
    title: "Genshin Impact",
    Publisher: "miHoYo",
    price: 0,
    originalPrice: 0,
    category: "PC Games",
    Genre: ["Action", "RPG", "Adventure"],
    stockQty: 100,
    rating: 3.9,
    releaseDate: "September 28, 2020",
    aboutGame:
      "Step into Teyvat, a vast world teeming with life and flowing with elemental energy. You and your sibling arrived here from another world.",
  },
  {
    _id: "07e9c9ff-39e9-4b5b-b859-9b1ba2e2c17c",
    img: "https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg",
    title: "Hades",
    Publisher: "Supergiant Games",
    price: 1499,
    originalPrice: 1999,
    category: "PC Games",
    Genre: ["Rogue-like", "Dungeon crawler"],
    stockQty: 30,
    rating: 4.8,
    releaseDate: "September 17, 2020",
    aboutGame:
      "Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles.",
  },
  {
    _id: "a5fe4a1d-8f64-4eb8-b8ef-c977e2a05946",
    img: "https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg",
    title: "Ghost of Tsushima",
    Publisher: "Sony Interactive Entertainment",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 18,
    rating: 4.9,
    releaseDate: "July 17, 2020",
    aboutGame:
      "In the late 13th century, a ruthless Mongol army invades Tsushima in a quest to conquer all of Japan. But for Jin Sakai, the conflict has just begun.",
  },
  {
    _id: "da050710-271b-44e0-bf1b-721bfad854fe",
    img: "https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg",
    title: "Ghost of Tsushima",
    Publisher: "Sony Interactive Entertainment",
    price: 2299,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 25,
    rating: 2.8,
    releaseDate: "July 17, 2020",
    aboutGame:
      "In Ghost of Tsushima, play as Jin Sakai, a samurai warrior on a quest to save his homeland from the Mongol invasion.",
  },
  {
    _id: "3865356f-f59b-4bfb-89d8-f11b76306f7a",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png",
    title: "The Last of Us Part II",
    Publisher: "Sony Interactive Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 15,
    rating: 4.8,
    releaseDate: "June 19, 2020",
    aboutGame:
      "Experience the emotional storytelling and unforgettable characters in The Last of Us Part II, developed by Naughty Dog.",
  },
  {
    _id: "d4199b9f-9b82-4beb-b776-18709d52980b",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/330px-Valorant_logo_-_pink_color_version.svg.png",
    title: "Valorant",
    Publisher: "Riot Games",
    price: 0,
    originalPrice: 0,
    category: "PC Games",
    Genre: ["First-person shooter"],
    stockQty: 100,
    rating: 4.7,
    releaseDate: "June 2, 2020",
    aboutGame:
      "Valorant is a 5v5 character-based tactical shooter where precise gunplay meets unique agent abilities.",
  },
  {
    _id: "5afd7daf-6617-43e0-b0c2-b15905523358",
    img: "https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png",
    title: "Final Fantasy VII Remake",
    Publisher: "Square Enix",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["RPG"],
    stockQty: 20,
    rating: 4.8,
    releaseDate: "April 10, 2020",
    aboutGame:
      "The world has fallen under the control of the Shinra Electric Power Company, a shadowy corporation controlling the planet's very life force as mako energy. In the sprawling city of Midgar, an anti-Shinra organization calling themselves Avalanche have stepped up their resistance.",
  },
  {
    _id: "930df3ba-a12f-4728-ba5b-52d43b130a16",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png",
    title: "Doom Eternal",
    Publisher: "Bethesda Softworks",
    price: 1899,
    originalPrice: 2499,
    category: "PC Games",
    Genre: ["First-person shooter"],
    stockQty: 25,
    rating: 4.6,
    releaseDate: "March 20, 2020",
    aboutGame:
      "Doom Eternal is the direct sequel to the award-winning and best-selling Doom (2016). Experience the ultimate combination of speed and power with the next leap in push-forward, first-person combat.",
  },
  {
    _id: "509a0d15-0151-4c1a-9ccb-1afbe49f2a9e",
    img: "https://upload.wikimedia.org/wikipedia/en/9/91/Nioh_2_cover_art.jpg",
    title: "Nioh 2",
    Publisher: "Koei Tecmo",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 13,
    rating: 4.5,
    releaseDate: "March 13, 2020",
    aboutGame:
      "Battle hordes of yokai in this masocore Action RPG. Create your protagonist and embark on an adventure through a myriad of locales across Japan during the Sengoku period.",
  },
  {
    _id: "1243a239-0ce1-4b37-8cad-e6c7fdc20319",
    img: "https://upload.wikimedia.org/wikipedia/en/9/94/Ori_and_the_Will_of_the_Wisps.jpg",
    title: "Ori and the Will of the Wisps",
    Publisher: "Xbox Game Studios",
    price: 1499,
    originalPrice: 1999,
    category: "PC Games",
    Genre: ["Platform","Adventure"],
    stockQty: 22,
    rating: 4.9,
    releaseDate: "March 11, 2020",
    aboutGame:
      "The highly anticipated sequel to Ori and the Blind Forest, Ori and the Will of the Wisps continues the tale of a young orphan destined for heroics through a visually stunning, hand-crafted world filled with new friends and foes that come to life in stunning detail.",
  },
  {
    _id: "d343b6da-aaef-4fa0-bcff-cb7c73773041",
    img: "https://upload.wikimedia.org/wikipedia/en/1/13/Cover_art_of_Star_Wars_Jedi_Fallen_Order.jpg",
    title: "Star Wars Jedi: Fallen Order",
    Publisher: "Electronic Arts",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 18,
    rating: 4.6,
    releaseDate: "November 15, 2019",
    aboutGame:
      "A galaxy-spanning adventure awaits in Star Wars Jedi: Fallen Order, a 3rd person action-adventure title from Respawn Entertainment.",
  },
  {
    _id: "0621a4f8-6b52-42be-bcf7-ccb98746ea80",
    img: "https://upload.wikimedia.org/wikipedia/en/2/22/Death_Stranding.jpg",
    title: "Death Stranding",
    Publisher: "Sony Interactive Entertainment",
    price: 2399,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action"],
    stockQty: 18,
    rating: 4.5,
    releaseDate: "November 8, 2019",
    aboutGame:
      "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience for the PlayStation®4 system.",
  },
  {
    _id: "48bb2de6-bb55-4173-b2dd-742ed68bf385",
    img: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
    title: "Red Dead Redemption 2 (PC)",
    Publisher: "Rockstar Games",
    price: 2099,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 30,
    rating: 5,
    releaseDate: "November 5, 2019",
    aboutGame:
      "Red Dead Redemption 2 for PC also includes free access to the shared living world of Red Dead Online featuring all previously released improvements and the latest content updates for the complete online experience including Frontier Pursuits and the specialist Roles of Bounty Hunter, Trader and Collector for players to progress through and earn unique rewards.",
  },
  {
    _id: "25f2d4de-01dd-435d-9ce4-ba842615676c",
    img: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
    title: "Red Dead Redemption 2",
    Publisher: "Rockstar Games",
    price: 2099,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 30,
    rating: 4.8,
    releaseDate: "November 5, 2019",
    aboutGame:
      "Red Dead Redemption 2 for PC also includes free access to the shared living world of Red Dead Online featuring all previously released improvements and the latest content updates.",
  },
  {
    _id: "eaac4ff6-6bcb-43da-94d4-8148fef10e81",
    img: "https://upload.wikimedia.org/wikipedia/en/b/b0/Persona_5_cover_art.jpg",
    title: "Persona 5 Royal",
    Publisher: "Atlus",
    price: 2599,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["RPG"],
    stockQty: 10,
    rating: 4.9,
    releaseDate: "October 31, 2019",
    aboutGame:
      "Prepare for an all-new RPG experience in Persona 5 Royal based in the universe of the award-winning series, Persona!",
  },
  {
    _id: "02757c58-0a13-434b-a4d8-6a91620a0c89",
    img: "https://upload.wikimedia.org/wikipedia/en/e/e7/The_Outer_Worlds_cover_art.png",
    title: "The Outer Worlds",
    Publisher: "Private Division",
    price: 2099,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["RPG"],
    stockQty: 20,
    rating: 4.4,
    releaseDate: "October 25, 2019",
    aboutGame:
      "Lost in transit while on a colonist ship bound for the furthest edge of the galaxy, you awake decades later only to find yourself in the midst of a deep conspiracy threatening to destroy the Halcyon colony.",
  },
  {
    _id: "7bd9ef43-47ce-4559-9edd-48b3128b8efb",
    img: "https://upload.wikimedia.org/wikipedia/en/e/e5/Control_game_cover_art.jpg",
    title: "Control",
    Publisher: "505 Games",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 22,
    rating: 4.5,
    releaseDate: "August 27, 2019",
    aboutGame:
      "After a secretive agency in New York is invaded by an otherworldly threat, you become the new Director struggling to regain Control.",
  },
  {
    _id: "809c3db0-5db6-4c0e-b140-40319ddfcd1d",
    img: "https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg",
    title: "Sekiro: Shadows Die Twice",
    Publisher: "Activision",
    price: 2499,
    originalPrice: 3499,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 12,
    rating: 4.6,
    releaseDate: "March 22, 2019",
    aboutGame:
      "Carve your own clever path to vengeance in the critically acclaimed adventure from developer FromSoftware, creators of Bloodborne and the Dark Souls series.",
  },
  {
    _id: "2e996ac9-a618-44eb-bf42-e6054eed3641",
    img: "https://upload.wikimedia.org/wikipedia/en/a/af/Cover_Art_of_Metro_Exodus.png",
    title: "Metro Exodus",
    Publisher: "Deep Silver",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["First-person shooter"],
    stockQty: 15,
    rating: 4.6,
    releaseDate: "February 15, 2019",
    aboutGame:
      "Metro Exodus is an epic, story-driven first person shooter from 4A Games that blends deadly combat and stealth with exploration and survival horror in one of the most immersive game worlds ever created.",
  },
  {
    _id: "717db9e0-88e7-4dba-ae8b-ba921e770a32",
    img: "https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg",
    title: "Apex Legends",
    Publisher: "Electronic Arts",
    price: 0,
    originalPrice: 0,
    category: "PC Games",
    Genre: ["Battle Royale", "First-person shooter"],
    stockQty: 100,
    rating: 4.6,
    releaseDate: "February 4, 2019",
    aboutGame:
      "Apex Legends is the next evolution of Battle Royale featuring a cast of unique characters, squad-based gameplay, and fast-paced combat.",
  },
  {
    _id: "446e33b6-e1b3-4099-8256-a39fcd1f1002",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9a/Among_Us_cover_art.jpg",
    title: "Among Us",
    Publisher: "Innersloth",
    price: 499,
    originalPrice: 999,
    category: "PC Games",
    Genre: ["Party", "Social deduction"],
    stockQty: 50,
    rating: 4.5,
    releaseDate: "June 15, 2018",
    aboutGame:
      "An online and local party game of teamwork and betrayal for 4-10 players...in space!",
  },
  {
    _id: "eacad3ec-8ec3-41ae-95f4-48be519af94e",
    img: "https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg",
    title: "God of War",
    Publisher: "Sony Interactive Entertainment",
    price: 2199,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 12,
    rating: 4.9,
    releaseDate: "April 20, 2018",
    aboutGame:
      "Kratos must adapt to unfamiliar lands, unexpected threats, and a second chance at being a father in God of War.",
  },
  {
    _id: "67714a50-93e8-4ca8-8bc7-035a7882921c",
    img: "https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg",
    title: "Monster Hunter: World",
    Publisher: "Capcom",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 20,
    rating: 4.6,
    releaseDate: "January 26, 2018",
    aboutGame:
      "Monster Hunter: World introduces a living, breathing ecosystem in which players take on the role of a hunter seeking and slaying ferocious beasts.",
  },
  {
    _id: "e274d61c-ea40-49a5-bfae-103e14fb8050",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9f/Pubgbattlegrounds.png",
    title: "PUBG",
    Publisher: "PUBG Corporation",
    price: 0,
    originalPrice: 0,
    category: "PC Games",
    Genre: ["Battle Royale", "First-person shooter"],
    stockQty: 100,
    rating: 4.6,
    releaseDate: "December 20, 2017",
    aboutGame:
      "PUBG is a battle royale shooter where 100 players fight to be the last person standing. Scavenge for weapons and gear to gain the upper hand.",
  },
  {
    _id: "e0531fc1-9d6a-4fe0-afb3-8cfb1b810eee",
    img: "https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg",
    title: "Super Mario Odyssey",
    Publisher: "Nintendo",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Platform"],
    stockQty: 20,
    rating: 4.8,
    releaseDate: "October 27, 2017",
    aboutGame:
      "Join Mario on a massive, globe-trotting 3D adventure and use his incredible new abilities to collect Moons so you can power up your airship, the Odyssey, and rescue Princess Peach from Bowser's wedding plans!",
  },
  {
    _id: "b3354abd-26b7-4a8e-832a-304e91050986",
    img: "https://upload.wikimedia.org/wikipedia/en/e/eb/Cuphead_%28artwork%29.png",
    title: "Cuphead",
    Publisher: "Studio MDHR",
    price: 1499,
    originalPrice: 1999,
    category: "PC Games",
    Genre: ["Run and gun", "Platform"],
    stockQty: 20,
    rating: 4.8,
    releaseDate: "September 29, 2017",
    aboutGame:
      "Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era.",
  },
  {
    _id: "f8d3d063-c527-4610-b034-1855cc446c77",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Divinity_Original_Sin_2_cover_art.jpg/330px-Divinity_Original_Sin_2_cover_art.jpg",
    title: "Divinity: Original Sin 2",
    Publisher: "Larian Studios",
    price: 2299,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["RPG"],
    stockQty: 12,
    rating: 4.8,
    releaseDate: "September 14, 2017",
    aboutGame:
      "The critically acclaimed RPG that raised the bar, from the creators of Baldur's Gate 3. Gather your party. Master deep, tactical combat. Venture as a party of up to 4 - but know that only one of you will have the chance to become a God.",
  },
  {
    _id: "62ec5c73-3deb-498a-9fde-785aefaf77bc",
    img: "https://upload.wikimedia.org/wikipedia/en/a/ae/Fortnite_Save_The_World.jpg",
    title: "Fortnite",
    Publisher: "Epic Games",
    price: 0,
    originalPrice: 0,
    category: "PC Games",
    Genre: ["Battle Royale", "Survival"],
    stockQty: 100,
    rating: 4.5,
    releaseDate: "July 25, 2017",
    aboutGame:
      "Fortnite is the living, action building game from the developer formerly known as Epic MegaGames.",
  },
  {
    _id: "e9f90e8a-08cb-4a9a-9110-dccbbe3fee37",
    img: "https://upload.wikimedia.org/wikipedia/en/2/21/Nier_Automata_cover_art.jpg",
    title: "NieR: Automata",
    Publisher: "Square Enix",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 14,
    rating: 4.7,
    releaseDate: "March 7, 2017",
    aboutGame:
      "Invaders from another world attack without warning - unleashing the machine lifeforms. To break the deadlock, a new breed of android infantry is sent into the fray: the YoRHa squad.",
  },
  {
    _id: "ce9038b4-2bd8-4259-85d3-640180cd4017",
    img: "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
    title: "The Legend of Zelda: Breath of the Wild",
    Publisher: "Nintendo",
    price: 2499,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 15,
    rating: 4.9,
    releaseDate: "March 3, 2017",
    aboutGame:
      "Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series.",
  },
  {
    _id: "a5a8b277-9da5-4e64-b058-aa031222c634",
    img: "https://upload.wikimedia.org/wikipedia/en/9/93/Horizon_Zero_Dawn.jpg",
    title: "Horizon Zero Dawn",
    Publisher: "Sony Interactive Entertainment",
    price: 2299,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 14,
    rating: 4.6,
    releaseDate: "February 28, 2017",
    aboutGame:
      "Experience Aloy's legendary quest to unravel the mysteries of a world ruled by deadly Machines.",
  },
  {
    _id: "b95dc44d-90d6-427e-8414-64de2791f2f3",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Hollow_Knight_first_cover_art.webp/274px-Hollow_Knight_first_cover_art.webp.png",
    title: "Hollow Knight",
    Publisher: "Team Cherry",
    price: 1499,
    originalPrice: 1999,
    category: "PC Games",
    Genre: ["Action", "Adventure", "Metroidvania"],
    stockQty: 18,
    rating: 4.7,
    releaseDate: "February 24, 2017",
    aboutGame:
      "Forge your own path in Hollow Knight! An epic action adventure through a vast, ruined kingdom of insects and heroes.",
  },
  {
    _id: "2dda7581-8e53-4dfe-929c-2c5554e6dc65",
    img: "https://upload.wikimedia.org/wikipedia/en/1/13/Titanfall_2.jpg",
    title: "Titanfall 2",
    Publisher: "Electronic Arts",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["First-person shooter"],
    stockQty: 20,
    rating: 4.92,
    releaseDate: "October 28, 2016",
    aboutGame:
      "Titanfall 2 features a single-player campaign packed with action and inventive twists, and a multiplayer mode that remains innovative and engaging.",
  },
  {
    _id: "126c6e1e-6a7b-4440-b7d4-9888c0649d77",
    img: "https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg",
    title: "Dark Souls III",
    Publisher: "Bandai Namco Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 16,
    rating: 4.8,
    releaseDate: "April 12, 2016",
    aboutGame:
      "Dark Souls III is the final journey in the action-packed Dark Souls franchise. Explore the epic and dark universe and face numerous challenges.",
  },
  {
    _id: "60f6bfcd-a2f2-4a47-9ab5-31ee0d9c8a03",
    img: "https://upload.wikimedia.org/wikipedia/en/2/29/Rise_of_the_Tomb_Raider.jpg",
    title: "Rise of the Tomb Raider",
    Publisher: "Square Enix",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 17,
    rating: 4.7,
    releaseDate: "November 10, 2015",
    aboutGame:
      "In Rise of the Tomb Raider, Lara Croft becomes more than a survivor as she embarks on her first Tomb Raiding expedition to the most treacherous and remote regions of Siberia.",
  },
  {
    _id: "5b524a7b-68b1-48d4-8f83-10c80471ad80",
    img: "https://upload.wikimedia.org/wikipedia/en/8/8f/Metal_Gear_Solid_V_The_Phantom_Pain_cover.png",
    title: "Metal Gear Solid V: The Phantom Pain",
    Publisher: "Konami",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure", "Stealth"],
    stockQty: 20,
    rating: 4.7,
    releaseDate: "September 1, 2015",
    aboutGame:
      "Metal Gear Solid V: The Phantom Pain is the series' true debut on next-gen consoles, expanding the user experience of peace-building and carrying the series to its next evolutionary level.",
  },
  {
    _id: "82d6e2eb-e391-4af3-a45b-c86f08e0dad2",
    img: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg",
    title: "The Witcher 3: Wild Hunt",
    Publisher: "CD Projekt",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["RPG"],
    stockQty: 20,
    rating: 4.9,
    releaseDate: "May 19, 2015",
    aboutGame:
      "The Witcher 3: Wild Hunt is a story-driven, open world RPG set in a visually stunning fantasy universe full of meaningful choices and impactful consequences.",
  },
  {
    _id: "a069b0ff-5f52-42d1-93f2-594898a6aa9e",
    img: "https://upload.wikimedia.org/wikipedia/en/6/68/Bloodborne_Cover_Wallpaper.jpg",
    title: "Bloodborne",
    Publisher: "Sony Computer Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "RPG"],
    stockQty: 18,
    rating: 4.7,
    releaseDate: "March 24, 2015",
    aboutGame:
      "Hunt your nightmares in the critically acclaimed action RPG, Bloodborne, from the creators of Dark Souls.",
  },
  {
    _id: "d8fa67a1-0acb-45b0-9e84-50f99f524a18",
    img: "https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png",
    title: "Grand Theft Auto V / GTA Online",
    Publisher: "Rockstar Games",
    price: 2999,
    originalPrice: 4999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 25,
    rating: 5,
    releaseDate: "September 17, 2013",
    aboutGame:
      "Grand Theft Auto V blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of the game's three lead characters, playing all sides of the game's interwoven story.",
  },
  {
    _id: "3c426a4e-9f5c-434d-822f-6589b805060e",
    img: "https://upload.wikimedia.org/wikipedia/en/0/00/Batman_Arkham_City_Game_Cover.jpg",
    title: "Batman: Arkham City",
    Publisher: "Warner Bros. Interactive Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 18,
    rating: 4.95,
    releaseDate: "October 18, 2011",
    aboutGame:
      "Batman: Arkham City builds upon the intense, atmospheric foundation of Batman: Arkham Asylum, sending players soaring into Arkham City, the new maximum security 'home' for all of Gotham City's thugs, gangsters and insane criminal masterminds.",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357385",
    img: "https://upload.wikimedia.org/wikipedia/en/4/42/Batman_Arkham_Asylum_Videogame_Cover.jpg",
    title: "Batman: Arkham Asylum",
    Publisher: "Warner Bros. Interactive Entertainment",
    price: 1999,
    originalPrice: 2999,
    category: "PC Games",
    Genre: ["Action", "Adventure"],
    stockQty: 15,
    rating: 4.8,
    releaseDate: "August 25, 2009",
    aboutGame:
      "Batman: Arkham Asylum exposes players to a unique, dark and atmospheric adventure that takes them to the depths of Arkham Asylum.",
  },

  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357386",
    img: "https://savekeys.net/wp-content/uploads/2022/01/cyberpunk-2077-xb-420x607.jpg",
    title: "Cyberpunk 2077 Key (XBOX ONE)",
    Publisher: "Warner Bros. Interactive Entertainment",
    price: 1699,
    originalPrice: 2699,
    category: "Xbox Games",
    Genre: ["RPG", "Action"],
    stockQty: 15,
    rating: 4.8,
    releaseDate: "August 25, 2009",
    aboutGame:
      "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character’s cyberwar, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357387",
    img: "https://savekeys.net/wp-content/uploads/2021/05/fifa-21-xbox-420x607.jpg",
    title: "FIFA 21 Key (XBOX ONE)",
    Publisher: "EA Sports",
    price: 1799,
    originalPrice: 3990,
    category: "Xbox Games",
    Genre: ["Sports"],
    stockQty: 20,
    rating: 4.7,
    releaseDate: "October 9, 2020",
    aboutGame:
      "FIFA 21 delivers more ways to team up and express yourself. Win as one in EA SPORTS™ FIFA 21, with new ways to team up on the street and in the stadium to enjoy even bigger victories together.",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357388",
    img: "https://savekeys.net/wp-content/uploads/2021/05/far-cry-5-xbox-420x607.jpg",
    title: "Far Cry 5 Key (XBOX ONE)",
    Publisher: "Ubisoft",
    price: 1299,
    originalPrice: 3999,
    category: "Xbox Games",
    Genre: ["Action", "Adventure"],
    stockQty: 25,
    rating: 4.6,
    releaseDate: "March 27, 2018",
    aboutGame:
      "Far Cry 5 brings an open-world action-adventure FPS game developed by Ubisoft. It‘s a standalone successor to its prequels, with a branching storyline, side quests, co-op mode, map editor and even a competitive multiplayer! The game presents a thrilling narrative with one of the series best antagonists, plenty of plot twists, and more!",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357389",
    img: "https://savekeys.net/wp-content/uploads/2021/05/witcher-3-420x607.jpg",
    title: "The Witcher 3: Wild Hunt Game of the Year Key (XBOX ONE)",
    Publisher: "CD Projekt",
    price: 899,
    originalPrice: 1299,
    category: "Xbox Games",
    Genre: ["RPG"],
    stockQty: 10,
    rating: 4.9,
    releaseDate: "May 19, 2015",
    aboutGame:
      "The Witcher: Wild Hunt is a story-driven open world RPG set in a visually stunning fantasy universe full of meaningful choices and impactful consequences. In The Witcher, you play as professional monster hunter Geralt of Rivia tasked with finding a child of prophecy in a vast open world rich with merchant cities, pirate islands, dangerous mountain passes, and forgotten caverns to explore.",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357390",
    img: "https://savekeys.net/wp-content/uploads/2020/04/gta-5-xbox-420x607.jpg",
    title: "Grand Theft Auto V: Premium Edition Key (Xbox One)",
    Publisher: "Rockstar Games",
    price: 1299,
    originalPrice: 2499,
    category: "Xbox Games",
    Genre: ["Action", "Adventure"],
    stockQty: 30,
    rating: 4.8,
    releaseDate: "September 17, 2013",
    aboutGame:
      "Grant Theft Auto V Rockstar Social Club key offers a game already known to most and loved by many. It’s the fifth action-adventure shooter game in the cultic series developed by Rockstar Games! Enter the vast open-world environment, visit different cities, hills, mountains, forests, and wastelands! GTA series was always known for their freedom of activity, and GTAV proves it once again!",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357391",
    img: "https://savekeys.net/wp-content/uploads/2020/03/playerunknowns_battlegrounds_pugb_xbox_one_1-420x607.jpg",
    title: "Playerunknown’s Battlegrounds (PUBG) Xbox One Key GLOBAL",
    Publisher: "PUBG Corporation",
    price: 899,
    originalPrice: 1999,
    category: "Xbox Games",
    Genre: ["Battle Royale"],
    stockQty: 18,
    rating: 4.5,
    releaseDate: "December 12, 2017",
    aboutGame:
      "PLAYERUNKNOWN? S BATTLEGROUNDS is a shooter in which the last survivor wins. Starting the match with nothing, the players have to find weapons and supplies to fight for the first place and become the last survivor. Battles in this realistic game with high voltage occur on a huge 8×8 km post-Soviet Black Sea island. PLAYERUNKNOWN? S BATTLEGROUNDS is developed on Unreal Engine 4 with constant help and support from players. Developers actively work together with the community of the game.",
  },
  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357392",
    img: "https://savekeys.net/wp-content/uploads/2020/03/assassin_s_creed_unity_xbox_one-420x607.png",
    title: "Assassin’s Creed Unity Xbox One Code",
    Publisher: "Ubisoft",
    price: 299,
    originalPrice: 999,
    category: "Xbox Games",
    Genre: ["Action", "Adventure"],
    stockQty: 50,
    rating: 4.4,
    releaseDate: "November 11, 2014",
    aboutGame:
      "Paris, 1789. The French Revolution turned the once beautiful city into the realm of fear and chaos. The streets are flowing rivers of blood of commoners who dared to resist the tyranny of the aristocracy. And while the French nation is a fratricidal war, a young man named Arno learns what forces actually are behind the revolution. The journey will lead him to the center of the battle for the fate of the nation, and will make him a real master assassin.",
  },

  {
    _id: "e49abeee-def8-4bbf-92b2-978dd1357386",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/ad18cfc6-a3bb-4d4f-8661-fe521a5073b9.jpg",
    title: "The Last of Us Remastered  for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 2999,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Action", "Adventure"],
    stockQty: 20,
    rating: 4.9,
    releaseDate: "June 19, 2020",
    aboutGame:
      "Experience the emotional storytelling and unforgettable characters in The Last of Us Part II, winner of over 200 Game of the Year Awards.",
  },
  {
    _id: "b53a7c22-856f-4d1e-bbb1-5e4f19b7a876",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/eac2a908-3c63-44d0-bf43-ecd456d06daf.jpg",
    title: "God of War: Ragnarok  for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 2499,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Action", "Adventure"],
    stockQty: 15,
    rating: 4.8,
    releaseDate: "November 09, 2022",
    aboutGame:
      "Kratos and Atreus embark on a mythic journey for answers and allies before Ragnarök arrives. From Santa Monica Studio comes the sequel to the critically acclaimed God of War (2018). Kratos and Atreus must journey to each of the Nine Realms in search of answers as they prepare for the prophesied battle that will end the world.",
  },
  {
    _id: "c09e7c15-9826-4f4b-a2c9-ec5684ab5c67",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/f967651a-c1b9-4cde-b0fd-eaee2580e056.jpg",
    title: "Spider-Man: Miles Morales for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 2999,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Action", "Adventure"],
    stockQty: 25,
    rating: 4.7,
    releaseDate: "November 12, 2020",
    aboutGame:
      "Experience the rise of Miles Morales as the new hero masters incredible, explosive new powers to become his own Spider-Man.",
  },
  {
    _id: "d1f72ad8-5f6c-4de2-97e4-44b9080d5e12",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/10e77101-1fcf-4a0c-8f81-d8b8e807d9d8.jpg",
    title: "Demon's Souls for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 2499,
    originalPrice: 4999,
    category: "PS Games",
    Genre: ["Action", "RPG"],
    stockQty: 10,
    rating: 4.6,
    releaseDate: "November 12, 2020",
    aboutGame:
      "Discover where the journey began with the remake of the Demon’s Souls, exclusively on PlayStation 5.",
  },
  {
    _id: "e27cb6b9-6842-4678-9e2b-9d87d3d1eaff",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/61d41c8d-97e5-48af-b3ad-a3b44ad3c208.jpg",
    title: "Ratchet & Clank: Rift Apart for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 1999,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Action", "Platformer"],
    stockQty: 30,
    rating: 4.9,
    releaseDate: "June 11, 2021",
    aboutGame:
      "Ratchet and Clank are back! Help them stop a robotic emperor intent on conquering cross-dimensional worlds, with their own universe next in the firing line.",
  },
  {
    _id: "f38a1f1d-3847-4986-a6d3-c8bb3b7c3e41",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/b4a7a161-4af4-4822-ac29-8fb75184e6ec.jpg",
    title: "Returnal for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 4999,
    originalPrice: 5999,
    category: "PS Games",
    Genre: ["Action", "Shooter"],
    stockQty: 18,
    rating: 4.7,
    releaseDate: "April 30, 2021",
    aboutGame:
      "After crash-landing on a shape-shifting world, Selene must search through the barren landscape of an ancient civilization for her escape.",
  },
  {
    _id: "e4fa5c2a-5b23-4d75-9256-2cb82e3a6c57",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/09e3d929-0be8-43df-b11c-2375d90f71d1.jpg",
    title: "Horizon Forbidden West",
    Publisher: "Sony Interactive Entertainment",
    price: 3999,
    originalPrice: 5999,
    category: "PS Games",
    Genre: ["Action", "RPG"],
    stockQty: 20,
    rating: 4.8,
    releaseDate: "February 18, 2022",
    aboutGame:
      "Join Aloy as she braves the Forbidden West a majestic but dangerous frontier that conceals mysterious new threats.",
  },
  {
    _id: "g58b9d2c-bf14-40d8-b9d2-9fabc9e8c9a7",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/b0101d29-e0ab-49f8-b424-933decb333b6.jpg",
    title: "Gran Turismo 7 for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 1999,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Racing", "Simulation"],
    stockQty: 12,
    rating: 4.7,
    releaseDate: "March 4, 2022",
    aboutGame:
      "Gran Turismo 7 builds on 22 years of experience to bring you the best features from the history of the franchise.",
  },
  {
    _id: "h4eaf2a6-cdea-4f8f-8fcd-8d3a6e3e8df8",
    img: "https://s3-ap-southeast-1.amazonaws.com/cdn.gamestheshop.com/boxart/c608a153-8ad7-41fa-8176-b7117de16d10.jpg",
    title: "Sackboy: A Big Adventure for PS",
    Publisher: "Sony Interactive Entertainment",
    price: 1999,
    originalPrice: 3999,
    category: "PS Games",
    Genre: ["Action", "Platformer"],
    stockQty: 25,
    rating: 4.8,
    releaseDate: "November 12, 2020",
    aboutGame:
      "Iconic PlayStation hero Sackboy bursts back into breathtaking action with a huge, fun, and frantic 3D multiplayer platforming adventure.",
  },

  {
    _id: "h4eaf2a6-cdea-4f8f-8fcd-8d3a6e3e8dg9",
    img: "https://m.media-amazon.com/images/I/71WFZhW7wQL._SX679_.jpg",
    title:
      "Logitech G29 Driving Force Racing Wheel and Floor Pedals PS5/PS4/PS3/PC/Mac (OPEN BOX)",
    Publisher: "Logitech",
    price: 19999,
    originalPrice: 36999,
    category: "Gaming Components",
    // Genre: [""],
    stockQty: 25,
    rating: 4.8,
    releaseDate: "November 12, 2020",
    aboutGame:
      "Stainless Steel Paddle Shifters, Adjustable Floor Pedals. Play your favourite games with the right gear and experience mind-blowing simulation with this Logitech G29 Racing Wheel Joystick. This joystick comes with Adjustable Floor Pedals for easy access, Desk and Rig mounts for easy setup, and lots more.",
  },

  {
    _id: "h4eaf2a6-cdea-4f8f-8fcd-8d3a6e3e8d10",
    img: "https://m.media-amazon.com/images/I/61d5d6dNkEL._SY450_.jpg",
    title: "Redgear Pro Wireless Gamepad with 2.4GHz Wireless Technology",
    Publisher: "Redgear",
    price: 1399,
    originalPrice: 1699,
    category: "Gaming Components",
    // Genre: [""],
    stockQty: 25,
    rating: 4.8,
    releaseDate: "November 12, 2020",
    aboutGame:
      " Gamepad comes equipped with2.4GHz wireless technology and supports up to 10 metres range, an ideal choice for those looking to enjoy your favourite games without the hassle of cables and wires.;The built-in lithium-ion battery in the gamepad can provide uninterrupted gameplay for up to 2 hours in a single charge for upto 30-minute.",
  },
];
